import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";

import { ChakraProvider } from "@chakra-ui/react";
import { TRPCReactProvider } from "~/trpc/react";
import SessionWrapper from "./_components/SessionWrapper";

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <SessionWrapper>
      <html lang="en">
        <body className={GeistSans.className}>
          <ChakraProvider>
            <TRPCReactProvider>{children}</TRPCReactProvider>
          </ChakraProvider>
        </body>
      </html>
    </SessionWrapper>
  );
}
